#include "nsISupports.idl"
#include "nsIDOMWindow.idl"

/**
 * This is a private interface that is used by Estonian
 * ID-card signing plugin for deep integration with Firefox.
 * It is used for showing native UI windows and manipulating
 * Firefox internals like cert stores and security modules.
 * This interface is only accessible for scripts with XPCOM access
 * and is not visible for web applications.
 */
[scriptable, uuid(be28a086-2234-429b-9bc4-74a652538c64)]
interface nsIEstEIDPrivate : nsISupports
{
  attribute boolean isConfigured;
  readonly attribute string log;
  readonly attribute string wl;

  string promptForSignPIN(in nsIDOMWindow aParent, in wstring subject,
                          in string docUrl, in string docHash,
                          in wstring pageUrl, in short pinPadTimeout,
                          in boolean retry, in short tries);
  void closePinPrompt(in nsIDOMWindow aParent);
  void showSettings(in nsIDOMWindow aWindow, in wstring pageUrl);
  void showPinBlockedMessage(in nsIDOMWindow aWindow, in short pin);

/*
  void showNotification(in nsIDOMWindow aWindow, in AString pageUrl);
  boolean isWhiteListed(in AString pageUrl);
  void   logMessage(in AString msg);
  void debugMessage(in AString msg);
  void errorMessage(in AString msg);
  void setWhitelist(in AString wl);
*/
};

%{C++

#define NS_ESTEIDPRIVATE_CONTRACTID "@id.eesti.ee/esteid-private;1"

%}
